{pkgs, ...}: {
  name = "bc";
  version = "1.08.2";
  notes = "from paper empc";

  src = pkgs.fetchurl {
    url = "https://ftp.gnu.org/gnu/bc/bc-1.08.2.tar.gz";
    # Verified with: nix-prefetch-url https://ftp.gnu.org/gnu/bc/bc-1.08.2.tar.gz
    # then `nix hash to-sri --type sha256 <hex>` to get the SRI form below.
    hash = "sha256-rkcP7EKXdWU+BCAV7cko0HyMOy/Fl2UXKjMNPYd4X4Y=";
  };

  # bc's grammar/lexer go through bison and flex during the build.
  extraNativeBuildInputs = [pkgs.bison pkgs.flex];

  build = {
    artifact = "bc/bc";
    phase = ''
      # A transformation that edits bc/scan.l (or bc/bc.y) makes the lexer/parser
      # source newer than its generated scan.c/bc.c. bc has no AM_MAINTAINER_MODE,
      # so that also trips the autotools auto-remake rules into running aclocal/
      # automake/autoconf -- none of which exist in the eval container, giving
      # "make[1]: *** [aclocal.m4] Error 127". Normalize mtimes so the generated
      # autotools files stay up to date and only a patched scan.l/bc.y is newer
      # than its generated .c (forcing just the flex/bison regen we want). A
      # no-op for the unpatched baseline (scan.c is regenerated byte-identically).
      find . -exec touch -h -d '2020-01-01 00:00:00' {} + 2>/dev/null || true
      touch -d '2020-01-02 00:00:00' aclocal.m4 configure config.h.in \
            Makefile.in */Makefile.in 2>/dev/null || true
      for s in bc/scan.l bc/bc.y; do
        [ -f "$s" ] && touch -d '2020-01-03 00:00:00' "$s" || true
      done

      # bc's link rule (bc/Makefile) emits $(LDFLAGS) before the objects but
      # $(LIBS) after them. A transformation that inserts klee_assume /
      # klee_make_symbolic leaves those references in scan.o, so the stub library
      # must come AFTER the objects or the link fails with "undefined reference to
      # klee_assume". Move -lklee-stubs from LDFLAGS to LIBS (cf. the make
      # harness). Harmless when no transformation is applied: with no references,
      # -Wl,--as-needed drops the stub lib.
      stubs=$({ echo "$LDFLAGS" | grep -oE '(-L[^ ]+|-lklee-stubs)' | tr '\n' ' '; } || true)
      export LDFLAGS=$(echo "$LDFLAGS" | sed -E 's|-L[^ ]+klee-intrinsic-stubs[^ ]*||g; s|-lklee-stubs||g')

      ./configure --without-readline
      # libbc.a is a build-time dependency of bc/bc; build the support
      # library first, then bc itself. Skip doc/ to avoid pulling in texinfo.
      make -j$NIX_BUILD_CORES -C lib LIBS="$stubs"
      make -j$NIX_BUILD_CORES -C bc bc LIBS="$stubs"
    '';
  };

  bitcode.extraCFlags = ["-Wno-implicit-function-declaration"];
  instrumented.extraCFlags = ["-Wno-implicit-function-declaration"];

  withLibcxx = false;

  symEnv = [
    "--sym-stdin"
    "40"
  ];

}
