#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""Compute per-program size / LoC / branch-count denominators from each
harness's baseline bitcode.

For every directory under containers/programs/ (except `hello`), this:
  1. Reads the harness `version` field.
  2. Builds the harness's `baselineBc` derivation via an inline nix
     expression that re-uses program-builder.nix.
  3. Runs pass/build/line-counter/line-counter on `<storePath>/program.bc`
     to get total_lines (default system-path filter on — matches what
     llvm-cov measures at replay time).
  4. Runs pass/build/branch-counter/branch-counter on the same bc
     to get total_outcomes (the denominator for branch coverage).
  5. Reads the bitcode file size in MB.

Emits a LaTeX table block to stdout that can be pasted into
programs.tex.
"""

import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROGRAMS = ROOT / "containers" / "programs"
LINE_COUNTER = ROOT / "pass" / "build" / "line-counter" / "line-counter"
BRANCH_COUNTER = ROOT / "pass" / "build" / "branch-counter" / "branch-counter"

# Harnesses whose canonical CLI binary differs from the harness directory name.
DISPLAY = {
    "diffutils": "diff",
    "libtiff": "tiffinfo",
    "libxml2": "xmllint",
}

# Not real benchmarks.
EXCLUDE = {"hello"}


def parse_version(name: str) -> str:
    text = (PROGRAMS / name / "default.nix").read_text()
    m = re.search(r'version\s*=\s*"([^"]+)"', text)
    if not m:
        raise RuntimeError(f"no version field in {name}/default.nix")
    return m.group(1)


def build_bc(name: str) -> Path:
    """Build the baselineBc derivation and return the path to program.bc."""
    expr = f"""
let
  flake = builtins.getFlake "git+file://{ROOT}";
  system = builtins.currentSystem;
  pkgs = import flake.inputs.nixpkgs {{
    inherit system;
    overlays = [flake.inputs.klee.overlays.default];
  }};
  kleePkgs = flake.inputs.klee.packages.${{system}};
  programBuilder = import {ROOT}/containers/lib/program-builder.nix {{
    inherit pkgs kleePkgs;
  }};
  harness = import ({ROOT}/containers/programs + "/{name}") {{ inherit pkgs; }};
  built = programBuilder harness;
in
  built.baselineBc
"""
    r = subprocess.run(
        [
            "nix",
            "build",
            "--impure",
            "--no-link",
            "--print-out-paths",
            "--expr",
            expr,
        ],
        capture_output=True,
        text=True,
    )
    if r.returncode != 0:
        raise RuntimeError(f"nix build failed for {name}:\n{r.stderr[-2000:]}")
    out = r.stdout.strip().splitlines()[-1]
    return Path(out) / "program.bc"


def run_counter(binary: Path, bc: Path) -> dict:
    r = subprocess.run([str(binary), str(bc)], capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(f"{binary.name} failed: {r.stderr}")
    return json.loads(r.stdout)


def fmt_int(n: int) -> str:
    """LaTeX `\\,` thousands separator (matches existing programs.tex)."""
    s = f"{n:,}"
    return s.replace(",", "{,}")


def main() -> int:
    names = sorted(
        p.name for p in PROGRAMS.iterdir() if p.is_dir() and p.name not in EXCLUDE
    )

    rows = []
    for name in names:
        display = DISPLAY.get(name, name)
        try:
            version = parse_version(name)
            print(f"[{name}] build...", file=sys.stderr, flush=True)
            bc = build_bc(name)
            size_mb = bc.stat().st_size / (1024 * 1024)
            print(f"[{name}] lines...", file=sys.stderr, flush=True)
            ljson = run_counter(LINE_COUNTER, bc)
            print(f"[{name}] branches...", file=sys.stderr, flush=True)
            bjson = run_counter(BRANCH_COUNTER, bc)
            lines = ljson["summary"]["total_lines"]
            branches = bjson["summary"]["total_outcomes"]
            rows.append((display, version, size_mb, lines, branches))
            print(
                f"[{name}] OK display={display} ver={version} "
                f"size={size_mb:.1f}MB loc={lines} branches={branches}",
                file=sys.stderr,
                flush=True,
            )
        except Exception as e:
            print(f"[{name}] FAILED: {e}", file=sys.stderr, flush=True)
            rows.append((display, "?", None, None, None))

    rows.sort(key=lambda r: r[0].lower())

    print()
    print("% generated by scripts/compute-program-stats.py")
    for display, version, size, loc, branches in rows:
        if size is None:
            line = f"    {display:<17} & {version:<15} & ---            & ---           & ---                 \\\\"
        else:
            line = (
                f"    {display:<17} & {version:<15} & "
                f"{size:>4.1f}           & "
                f"{fmt_int(loc):>11}    & "
                f"{fmt_int(branches):>10}             \\\\"
            )
        print(line)
    return 0


if __name__ == "__main__":
    sys.exit(main())
