{pkgs, ...}: {
  name = "gzip";
  version = "1.14";
  notes = "";

  src = pkgs.fetchurl {
    url = "https://ftp.gnu.org/gnu/gzip/gzip-1.14.tar.gz";
    # Verified with: nix-prefetch-url https://ftp.gnu.org/gnu/gzip/gzip-1.14.tar.gz
    # then `nix hash convert --hash-algo sha256 --to sri <hex>` to get the SRI form below.
    hash = "sha256-YT1upE8SSNc3DHzN7uDdABegnmw53olLPG8D+YEZHGs=";
  };

  build = {
    artifact = "gzip";
    phase = ''
      # gl_cv_crc_pclmul=no forces gzip's PCLMUL CRC32 path off. KLEE has
      # no model for llvm.x86.pclmulqdq nor for the __builtin_cpu_supports
      # runtime dispatch (which links to __cpu_model and aborts KLEE during
      # global init). Disabling at configure also keeps the instrumented
      # binary on the portable CRC32 path — coverage is unaffected.
      ./configure --disable-nls --disable-dependency-tracking gl_cv_crc_pclmul=no
      # eval-transformations stages the source tree with `cp -r`, which does
      # NOT preserve mtimes (the Nix baseline gets them from tarball
      # extraction). gzip 1.14 ships automake "maintainer" rebuild rules
      # (aclocal.m4 -> config.hin -> Makefile.in -> Makefile), so a scrambled
      # mtime ordering makes `make` think those generated files are stale and
      # tries to re-run aclocal-1.17/automake-1.17/autoheader — none of which
      # exist in the eval image. Normalising every file to one identical
      # timestamp AFTER configure (configure itself writes fresh-mtime files)
      # makes `make` treat the prebuilt autotools outputs as up-to-date, so it
      # never invokes the missing tools. Harmless on the Nix baseline build,
      # where mtimes were already consistent.
      find . -exec touch -d '2020-01-01 00:00:00' {} +
      # Same lib-then-binary pattern as grep/diffutils: build the gnulib helper
      # archive first so the gzip binary can link against it, then build gzip
      # alone to avoid the texinfo dep pulled in by the top-level `all` target
      # (doc/gzip.info).
      make -j$NIX_BUILD_CORES -C lib
      # gzip declares version.{c,h} as automake BUILT_SOURCES, which are only
      # auto-generated by the `all`/`check` targets. Targeting `make gzip`
      # skips that step, so generate them explicitly before compiling.
      make -j$NIX_BUILD_CORES version.h version.c
      # A source-level transformation may insert KLEE intrinsics (e.g.
      # klee_get_value_i32 to concretize the deflate hash). Those resolve from
      # libklee-stubs.a, which the builder puts on $LDFLAGS as
      # `-L<dir> -lklee-stubs`. But gzip's link rule expands as
      # `$(LINK) $(OBJECTS) ...` with $(LDFLAGS) *before* the objects, and
      # gzip's Makefile links with -Wl,--as-needed
      # (IGNORE_UNUSED_LIBRARIES_CFLAGS): a static archive seen before any
      # undefined symbol is dropped, so the stubs vanish and the native link
      # (which get-bc needs to extract bitcode) fails with "undefined
      # reference to klee_get_value_i32". Re-supplying the stub archive via
      # LIBS (appended AFTER the objects) with --no-as-needed pulls the needed
      # members. We reuse the exact -L/-l tokens already on $LDFLAGS so this
      # carries no hard-coded store path. On the baseline (no intrinsics) the
      # archive contributes nothing — an inert extra lib.
      make -j$NIX_BUILD_CORES gzip \
        LIBS="-Wl,--no-as-needed $LDFLAGS -Wl,--as-needed"
    '';
  };

  bitcode.extraCFlags = ["-Wno-implicit-function-declaration"];
  instrumented.extraCFlags = ["-Wno-implicit-function-declaration"];

  withLibcxx = false;

  symEnv = [
    "--sym-args"
    "0"
    "2"
    "2"
    "A"
    "--sym-files"
    "1"
    "50"
  ];
}
